name: Upload Podcast

on:
  #schedule:
   # - cron: '0 22 * * *' # This cron expression means "every day at 10 PM UTC"
  workflow_dispatch: # Allows manual triggering
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.0' # Specify the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run script
        env:
          PODBEAN_CLIENT_ID: ${{ secrets.PODBEAN_CLIENT_ID }}
          PODBEAN_CLIENT_SECRET: ${{ secrets.PODBEAN_CLIENT_SECRET }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python upload.py