name: Scheduled Job

on:
  schedule:
    # Run at 13:00 UTC every day, which is 5:00 AM PST
    - cron: '0 13 * * 2-6'
  workflow_dispatch:  # This allows manual triggering of the workflow

jobs:
  run-scheduled-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Write Google Cloud Service Account Key
      run: echo "${{ secrets.AI_BRIEFING_ROOM_KEY_JSON }}" > ai-briefing-room-key.json

    - name: Verify Google Cloud Service Account Key
      run: cat ai-briefing-room-key.json

    - name: Run backend script
      run: python3 newsLetter/newsletter.py
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        OPENAI_ORGANIZATION_ID: ${{ secrets.OPENAI_ORGANIZATION_ID }}
        GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/ai-briefing-room-key.json
